apiVersion: v1
kind: Service
metadata:
  name: device-data-event-producer
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  selector:
    app: device-data-event-producer
