---
version: '3.5'
services:
  kafka:
    image: 'bitnami/kafka:latest'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:29092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - 8090:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: PLAINTEXT://kafka:29092
  device-data-event-producer:
    container_name: device-data-event-producer-container
    image: device-data-event-producer-image:latest
    depends_on:
      - kafka
    ports:
      - 9000:9000
    environment:
      KAFKA_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:29092
  device-data-event-consumer:
    container_name: device-data-event-consumer-container
    image: device-data-event-consumer-image:latest
    depends_on:
      - kafka
    ports:
      - 9001:9001
    environment:
      KAFKA_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:29092
  device-data-event-processor:
    container_name: device-data-event-processor-container
    image: device-data-event-processor-image:latest
    depends_on:
      - kafka
    ports:
      - 9002:9002
    environment:
      KAFKA_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:29092
  points-allocator:
    container_name: points-allocator
    image: points-allocator-image:latest
    depends_on:
      - kafka
    ports:
      - 9003:9003
    environment:
      KAFKA_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:29092
  notification-sender:
    container_name: notification-sender
    image: notification-sender-image:latest
    depends_on:
      - kafka
    ports:
      - 9004:9004
    environment:
      KAFKA_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:29092