---
version: '3.5'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.1.0
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    container_name: sn-zookeeper
  kafka:
    image: confluentinc/cp-kafka:7.1.0
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    container_name: sn-kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - 8090:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: PLAINTEXT://kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
  device-data-event-producer:
    container_name: device-data-event-producer-container
    image: device-data-event-producer-image:latest
    depends_on:
      - kafka
    ports:
      - 9000:9000
    environment:
      KAFKA_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
  device-data-event-consumer:
    container_name: device-data-event-consumer-container
    image: device-data-event-consumer-image:latest
    depends_on:
      - kafka
    ports:
      - 9001:9001
    environment:
      KAFKA_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
  device-data-event-processor:
    container_name: device-data-event-processor-container
    image: device-data-event-processor-image:latest
    depends_on:
      - kafka
    ports:
      - 9002:9002
    environment:
      KAFKA_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
  points-allocator:
    container_name: points-allocator
    image: points-allocator-image:latest
    depends_on:
      - kafka
    ports:
      - 9003:9003
    environment:
      KAFKA_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
  notification-sender:
    container_name: notification-sender
    image: notification-sender-image:latest
    depends_on:
      - kafka
    ports:
      - 9004:9004
    environment:
      KAFKA_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092